on:
  workflow_dispatch:
  push:
    branches: [ "v5" ]

permissions:
  contents: write

jobs:
  update:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - run: cargo install resvg
      - run: pip install -Ur requirements.txt
      - run: python render.py -z 1 2 3 4 5 6 7 8 9
      - run: |
            git config --global user.name "github actions"
            git config --global user.email "username@users.noreply.github.com"
      - run: git add .
      - run: git commit -am "update @ $(date +%Y%m%dT%H:%M:%S%Z)"
      - run: git push
