on:
  workflow_dispatch:
  push:

permissions:
  contents: write

env:
  LOG: INFO

jobs:
  update:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: resvg
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: usvg
      - run: pip install -Ur requirements.txt
      - run: python render.py
      - run: echo "message=update @ $(date +%Y%m%dT%H:%M:%S%Z)" >> "$GITHUB_ENV"
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: ${{ env.message }}