on:
  workflow_dispatch:
  push:
    branches: [ "v5" ]

permissions:
  contents: write

jobs:
  update:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - run: cargo install resvg usvg
      - run: pip install -Ur requirements.txt
      - run: python /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tile_renderer/types/skin/_generate_default.py
      - run: python render.py
      - run: |
            git config --global user.name "github actions"
            git config --global user.email "username@users.noreply.github.com"
      - run: git add .
      - run: git commit -am "update @ $(date +%Y%m%dT%H:%M:%S%Z)"
      - run: git push
